### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by aomranj** [themech/ms2txt#1]
I got this error when I try to use it

Traceback (most recent call last):
  File "ms2txt/ms2txt.py", line 49, in <module>
    main()
  File "ms2txt/ms2txt.py", line 40, in main
    em_file = MSEMasterFile('EMASTER', options.precision)
  File "/Users/aomranj/Downloads/Daily-MEC_Saudi_All-21_03_2019/ms2txt/metastock/files.py", line 259, in __init__
    self.stocks.append(self._read_file_info(file_handle))
  File "/Users/aomranj/Downloads/Daily-MEC_Saudi_All-21_03_2019/ms2txt/metastock/files.py", line 230, in _read_file_info
    dfi.stock_symbol = file_handle.read(14).strip('\x00')
TypeError: a bytes-like object is required, not 'str'

**Comment by aomranj** [comment]
??

**Comment by themech** [comment]
Hmm, for sure the tool provided is not Python3-ready, it was created back in 2009. But I think it is not the case here. Could you please provide me some basic info that could be useful when reproducing the error you're getting:
* which python version are you using (available after running `python -v` command)
* which operating system are you running (windows/mac/linux)
* optionally - where did you obtain the Mestastock data

**Comment by aomranj** [comment]
Thank you for support me
I used python version 3.7.1 on Mac system

**Comment by themech** [comment]
I've updated the source code so it works with Python3. 
I also added an option to specify the stock names encoding. By default it is set to `ascii` but in case your Metastock files use localized names with non-ascii characters, the string decoding may break. In such a case you can specify the correct encoding with the `-e` option, for example for Arabic names this can be `-e cp1256`.

Please let me know if that helps.

**Comment by aomranj** [comment]
Thank you TheMech for support
I Got error when I try to decode files
you can use my metastock files in this link

**Comment by themech** [comment]
@aomranj I think I can see some issues now. The current version of the code makes some assumptions about Metastock files that were true back in 2009 but aren't true anymore. I should be able to fix it in a day or two.

**Comment by aomranj** [comment]
@themech
I need your project in my work
Can you help me to fix the error in your code?

**Comment by themech** [comment]
@aomranj sorry, it took longer than I expected as your files were in newer format than the files I was using back in the days.
Anyway, I think I've covered the basic feature set. I should work with the files you provided regardless if you use python2 or python3.

Please let me know if that works now.

**Comment by aomranj** [comment]
**Thank you
Now Work good**
