### ISSUE TITLE
ascii codec not working

### ISSUE THREAD

**Issue by nabil-ha** [themech/ms2txt#3]
the ascii codec isn't working, I believe the problem would be either from my terminal or from data itself, maybe it has some arabic characters. Any solutions?

Error while reading the stock name. Did you specify the correct encoding?
Current encoding: ascii, error message: 'ascii' codec can't decode byte 0xc7 in position 0: ordinal not in range(128)

**Comment by themech** [comment]
I was porting this project to Python 3 not so long ago and was testing this against metastock file with Arabic characters. Is the file you're using publicly available so I can test it myself and add fixes if needed?

**Comment by nabil-ha** [comment]
Hey themech, sorry I forgot to close this issue, i found the solution, it only was to specify the coding to be cp1250
python ms2txt.py --all -e cp1250
But I have another question, is there any scripts out there or even yours can decrypt intraday metastock data?

**Comment by themech** [comment]
I'm glad it worked. Please let me know if you encounter other issues.
