### ISSUE TITLE
Referencing outdated for DataFileInfo

### ISSUE THREAD

**Issue by kennethlimcp** [themech/ms2txt#4]
The following lines should be using `DatFile` instead

- https://github.com/themech/ms2txt/blob/master/metastock/files.py#L86
- https://github.com/themech/ms2txt/blob/master/metastock/files.py#L97
- https://github.com/themech/ms2txt/blob/master/metastock/files.py#L362

**Comment by themech** [comment]
It looks like you're right, thank you for letting me know. Somehow I missed it during refactoring and surprisingly it worked when I was smoke-testing it. I'll try to fix it in a day or two and push a new version.

**Comment by themech** [comment]
Fixed in https://github.com/themech/ms2txt/commit/1ad3b8b0e8c75839847050b9e3b3aeeb658a0612
